services:
  sktorrent-hybrid:
    build: .
    container_name: sktorrent-hybrid
    restart: unless-stopped
    ports:
      - "127.0.0.1:7000:7000"
    environment:
      - REALDEBRID_API_KEY=${REALDEBRID_API_KEY}
      - SKT_UID=${SKT_UID}
      - SKT_PASS=${SKT_PASS}
      - ADDON_API_KEY=${ADDON_API_KEY}
      - STREAM_MODE=${STREAM_MODE:-RD_ONLY}  # NOVÁ PROMĚNNÁ
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - sktorrent-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/.acme.sh/oci.kukal.cz_ecc/fullchain.cer:/etc/ssl/certs/cert.pem:ro
      - /root/.acme.sh/oci.kukal.cz_ecc/oci.kukal.cz.key:/etc/ssl/certs/key.pem:ro
    depends_on:
      - sktorrent-hybrid
    networks:
      - sktorrent-internal

networks:
  sktorrent-internal:
    driver: bridge
